### ISSUE TITLE
Project OpenSpades_Resources dont want to compile in MSVC

### ISSUE THREAD

**Issue by evorios** [yvt/openspades#316]
**openspades\Resources\downloadpak.sh** dont work in Windows OS, because it is unixshell-script.
You can use powershell-script for this.

**Comment by yvt** [comment]
`mkpak.sh` also should be ported to PowerShell, VBScript, batch file, or something. Creating a zip file in PowerShell seems to be possible according to [this post](http://stackoverflow.com/questions/1153126/how-to-create-a-zip-archive-with-powershell).

**Comment by feikname** [comment]
**Note:** There is workaround for now is using Bash on Ubuntu on Windows, which works fine for most occasions, incudsng graphical applications and command-lineshell/bash scripts.

**Comment by noway421** [comment]
it needs to have this feature enabled in window developer console afaik (or something like that), it's not enabled by default. moreover, getting it to work with cmake on windows might be tricky because cmake wouldn't know that bash should be resolved to "ubuntu on windows" bash.

another option is cygwin btw, in that case bash directory is written in `PATH` and available globally.

but surely writing the ported version would be a better option, if that takes enough priority for itself.
