### ISSUE TITLE
Texture support?

### ISSUE THREAD

**Issue by VinnyVicious** [yvt/openspades#380]
Is it possible to assign textures to blocks, instead of just colors?

**Comment by Chameleonhider** [comment]
Yes it is possible.

But currently used map format supports only colours. So if you want to add textures, you will either have to:
* make all textures the same
* texture type rely on block colour
* have different maps for different textures
* make different map format

There's a lot of things you can improve besides making the game more CPU / GPU requiring.
Remember that you could run AoS 0.x on your grandmother's rig.

**Comment by yvt** [comment]
Ancient version had one. Every block had the same texture because having different textures breaks compatibility with AoS 0.75β. I removed it to make OpenSpades run as fast as possible, to keep the rendering code as simple as possible, and for a technical reason. 

There's no plan to add it again.

![shot0047 tga](https://cloud.githubusercontent.com/assets/5253988/12680768/e55e10c8-c6ee-11e5-8bcd-92b77aa39aa1.jpg)

**Comment by tigercoding56** [comment]
> . I removed it to make OpenSpades run as fast as possible, to keep the rendering 
> 
> There's no plan to add it again.
> 
> 

now that computers are faster maybe it is time to revisit textures
