### ISSUE TITLE
_TrN macro always load catalog translations as singular

### ISSUE THREAD

**Issue by feikname** [yvt/openspades#469]
Translations using _TrN macro always stay in the singular if loaded from a catalog (e.g. `core_locale: pt_br`).

The root of the issue are those 2 files:
 * `Sources/core/string.h`
 * `Sources/core/string.cpp`

Specially the `GetTextRawPlural()` and `GetCatalogOfLanguage()->Find()` functions.

**Comment by theunknownxy** [comment]
The parser for the plural expressions seems to be broken, because things like "!=" or ">" won't be parsed.
The reason for this seems to be that [ParseLogical](https://github.com/yvt/openspades/blob/6a7af96daf7c67c1b34d487c2e948dafdc31d2ff/Sources/Core/Strings.cpp#L447-L447) is never called. I guess @yvt needs to take a look at this, because I have no idea how the grammar should look like.
