### ISSUE TITLE
SMG Balancing (Increase TTK, Distance-based damage fall-off)

### ISSUE THREAD

**Issue by Rafael450** [yvt/openspades#558]

**Comment by feikname** [comment]
Could you please further explain why you think SMG needs to be nerfed?

I am also adding this to the next-gen label, because we obviously can't to that in the current versions.

**Comment by DetectDefective** [comment]
Shitpost aside, when it's possible, it'd be nice if the SMG received a nerf. As it is, the gun is extremely easy to score kills with, even at long range. I'm referring to AoS 0.75, since the community rejected 0.76, which increased the Rifle's accuracy.

Reducing the damage would help increase the time-to-kill, even if it's just slightly.

Head damage, from 75 (two shots) to 45 (three shots).
Torso damage, from 29 (four shots) to 20 (five shots).
Limb damage, from 18 (six shots) to 15 (seven shots).

The drops, especially in headshot, seem large, but the time-to-kill is only being increased by one tenth of a second for each grouping, or two-to-three tenths of a second if you mix them up.

Fall-off damage at a range would also help, but that would be a brand new thing as well.

**Comment by VelocityRa** [comment]
Completely agree with @DetectDefective about the nerfs.

I like the idea of damage falloff after a certain distance too.

**Comment by NotAFile** [comment]
This is something the OpenSpades team can not fix, really. Damage is dealt server-side, so a server change is required. It might be necessary to change it in OS too if it is used in lag-compensation, but at it's core this is a server issue.

**Comment by yvt** [comment]
I also agree with @DetectDefective. 

The damage calculation against players is done entirely server-side, so we could write a simple pyspades script to modify the damage formula. But after that, someone needs to contact server admins to have the script installed on a server.

The damage calculation against voxels is done client-side, but lowering damage is virtually possible by managing a "second health bar" for each voxel inside a server. 

Anyway, this isn't something that can be changed inside OpenSpades.

**Comment by NotAFile** [comment]
I opened an Issue at https://github.com/piqueserver/piqueserver/issues/59
