### ISSUE TITLE
Translation update notification

### ISSUE THREAD

**Issue by damienflament** [yvt/openspades#566]
I there a way to be notified of translation updates needed ?
This could be for each POT file update or before any new releases.

Email addresses mentioned in the PO file for the _Language-Team_ key can be used to send an e-mail to each translation team.

**Comment by NotAFile** [comment]
There are a number of services that offer free management of translation and translation teams, it might be a good idea to look into those.

http://zanata.org is a quick example I found, but I used a different tool on another project and it was really good.

**Comment by damienflament** [comment]
Well, I think about something more simple. But, if someone in the OpenSpades team want to manage a translation platform, it would be great !

This might be necessary if OS grow up in features (so, in translated terms) or in supported languages.

**Comment by feikname** [comment]
Regarding translation platforms:

[*Poeditor*](https://poeditor.com/) (Doesn't seem to be affliated with *Poedit*) looks like a good option, its [unlimited for open-source](https://poeditor.com/pricing/) projects and their website has been around for quite a bit of time already.

Another one that looks like a good option is [*Zanata*](http://zanata.org/), which is [open-source](https://github.com/zanata/) and is also free.

Weirdly, zanata website doesn't use https protocol. With the [general move torwards `https://`](https://blog.mozilla.org/security/2015/04/30/deprecating-non-secure-http/) (and by consequence, getting rid of http) from major browsers, I think it's an notable drawback in the website.

Another options could be the paid ones, *Transifex* (which I don't like much by the way) and *Crowdin*. But I'm unsure if anyone is willing to pay for these paid services, even more so with free ones available. (Although I certainly would like to use Crowdin 😄)

Of couse we could also stay with our current approach, and manually (or maybe using a GitHub trigger?) notify translators to [update their translations](https://github.com/yvt/openspades/wiki/Translation#translating)]. However, we don't get some of the advantages of having an translation platform:
 * Ease of translation for non tech-savvy people 
   * Writing an wiki article explaining to newcomers the translation process is, in my opinion, hard (due to it being deeply tied with the repository source code and the git process), and I'm still unsure if the current guide is doing a good job.
 * The UI might be better than the *Poedit* one
 * Keeping track of translation progress for each language
 * Notification of translation updates for translators
 * Less pull request clutter due to translations (currently, 18.125% of the pull requests are tagged as `PR: Translation`)

**Comment by IBPX** [comment]
> Another options could be the paid ones, Transifex (which I don't like much by the way) and Crowdin.

Those are both free for open-source projects.

**Comment by yvt** [comment]
I created projects in [Zanata](https://translate.zanata.org/project/view/openspades?dswid=9108), [Crowdin](https://crowdin.com/project/openspades) and some other platforms to check their features. Here's what I found out:

- Generally, I felt that the user experience of these two services was better than other alternatives. Also, they both provide communication spaces for translators (i.e., forums and chat boxes). 
- From the point of view of developers, both of them provide APIs and CLI tools which allow us to import and export translations, so it should be a piece of cake to integrate them into the current git code base.
- Each service has their own unique benefits. For example, Crowdin has a feature to notify translators about new strings added to the project, which is exactly what we're looking for. On the other hand, Zanata got a unique feature that none of others had: the support for managing multiple versions. Basically we can work on 0.1.x while working on 0.2.x at the same time. 
 
<img width="755" alt="screen shot 2017-02-03 at 5 05 42" src="https://cloud.githubusercontent.com/assets/5253988/22602397/64961c30-ea86-11e6-91af-822761f6bb7f.png">

Feel free to join these projects and test them by yourself. Note that you'll need to create an account for each service to use it.

> Weirdly, zanata website doesn't use https protocol. With the general move torwards https:// (and by consequence, getting rid of http) from major browsers, I think it's an notable drawback in the website.

Not exactly. At least the translation app website (https://translate.zanata.org/) supports and forces the use of HTTPS. The main website (http://zanata.org/) doesn't, though.

<img width="991" alt="screen shot 2017-02-03 at 20 44 42" src="https://cloud.githubusercontent.com/assets/5253988/22599418/3a9a6348-ea7a-11e6-928b-d5856f911c1b.png">

> > Another options could be the paid ones, Transifex (which I don't like much by the way) and Crowdin.
>
> Those are both free for open-source projects.

And I just got the approval response from Crowdin for the open-source plan.

**Comment by NotAFile** [comment]
@yvt I think you should decide what to use so people can get started with translation without duplicating effort

**Comment by yvt** [comment]
I'd like to adopt [Crowdin](https://crowdin.com/project/openspades) as OpenSpades' translation platform experimentally. If you have any questions, concerns or objections, please reply to this issue.
