### ISSUE TITLE
Openspades PPA is dead

### ISSUE THREAD

**Issue by Soulusions** [yvt/openspades#722]
Cannot find the ppa for openspades by fontoro, returns the error:
`Cannot add PPA: 'ppa:~fantoro/ubuntu/openspades'.
The user named '~fantoro' has no PPA named 'ubuntu/openspades'
Please choose from the following available PPAs:
`
There are no PPAs after that for some reason....

**Comment by feikname** [comment]
Somehow I missed this issue.. Sorry for the late response.

fantoro deleted his PPA because he was not willing to maintain it anymore (#700)

There's plans for adding official packages in the future though: #81 

Also, plase note OpenSpades is available in Snap and [Snapcraft](https://flathub.org/apps/details/jp.yvt.OpenSpades) (https://github.com/yvt/openspades/issues/788#issuecomment-479356535) forms for easy installs.
