### ISSUE TITLE
Stuck when uncrouching in the air

### ISSUE THREAD

**Issue by Clogal** [yvt/openspades#857]
Player gets stuck when uncrouching in the air and feets gets below ground.
Its quite easy to reproduce, and is pretty annoying. 
Here's a video showing it : https://youtu.be/oiu0fAtlq5E

**Comment by VierEck** [comment]
also like to add that when this bug doesnt happen when uncrouching in the air more often the climb animation seems to get triggered instead. i think that bug is related to this one here. 
in the original voxlap client the player always shoots immediatly up so that their feet align to the ground instantly. 

both the occurences described in the original post by clogal and the one i describe causes the player to de-accelerate greatly upon landing on the ground. but this happens only client side. the server will still calculate your speed and position as if you were a voxlap player so your speed and position will be different between what you and the other players perceive causing lag. 

movement should be as close to the original as possible so deviations between client and server, aka. lag, are kept to the minimum. 

this also gives you a harder time playing on the parkour gamemode when most of ur velocity gets stripped away when you land on a block.
