### ISSUE TITLE
Cannot vote-kick players whose names start with #

### ISSUE THREAD

**Issue by Techlinious** [yvt/openspades#869]
players with # at the start of their name eg: #NAME, will not respond to commands such as /votekick.

**Comment by JohnDowson** [comment]
Is that really a problem? You can use player number instead.

**Comment by Clogal** [comment]
I think this is related to the server, some servers have a fix for that bug

**Comment by NotAFile** [comment]
Yes, this is a server issue. The client just sends server commands like a normal chat message, it does not treat them specially in any way.

Upgrading to a modern server like piqueserver will fix this.

**Comment by feikname** [comment]
You could try kicking them by their ID instead, e.g. `/votekick #21`.

If that doesn't work, unfortunately the server you are on has a broken votekick system and you should advise them to fix it or upgrade to a newer server software such as piqueserver.

Since this is not something OpenSpades can fix, I'm closing the issue.
