### ISSUE TITLE
Windows ocassionally crashes after downloading snapshot

### ISSUE THREAD

**Issue by Oxlot** [yvt/openspades#878]
The game ocassionally crashes Windows after fully downloading the server snapshot by THREAD_STUCK_IN_DEVICE_DRIVER. This has happened to me 3 times to date, it had never happened before on any other PC.

**Notes about the crash:**
- I'm not running OpenSpades on fullscreen.
- I'm using YSR mode for audio.
- All graphic settings are on Low.

**My PC specifications:**
Windows Home 1903
AMD Ryzen 5 3550H
GTX 1650 (i run the game with this one)
RAM DDR4 8GB

**Comment by feikname** [comment]
This is probably on your side and not in OpenSpades code (i could be wrong tho). Did you have this problem with any other games?

Here's a couple stuff you can try:
 * Try to update your video drivers (both GPUs) and Windows version (1909 is the latest). Make sure you have latest BIOS version as it might very well fix your issue.
 * Try to run OpenSpades in the integrated GPU to check if the issue goes away. If that happens, you will know the problem is exclusively with the dGPU.
 * Try to use OpenSpades with a hardware temperature monitoring tool and check if anything goes really high (e.g. 95 celsius), high temperatures are unlikely but could be the cause.

I would also check in your notebook manufacturer's forum or similar if anyone else had the same problem as you. In worst case, it could be defective hardware.

**Comment by Oxlot** [comment]
I think everything is fixed now, i updated my integrated graphics. Seems that RefreshRateService.exe stopped working while i was playing OpenSpades and that was the reason of those crashes.
