### ISSUE TITLE
Crashing while moving cursor on server list

### ISSUE THREAD

**Issue by second2050** [yvt/openspades#893]
The game crashes on my machine after moving the cursor on the server list and dumps a crashdmp file to my desktop.

[OpenSpadesCrash37304265.zip](https://github.com/yvt/openspades/files/4538784/OpenSpadesCrash37304265.zip)

**Comment by yvt** [comment]
The crash seems to have been caused by the OpenAL driver (OpenAL Soft) similarly to #867. Can you try switching the audio renderer to YSR?
<img alt="Screen Shot 2019-11-16 at 18 05 42" width="527" src="https://user-images.githubusercontent.com/5253988/68990874-bc47da00-089b-11ea-9708-6e5d037dd5bf.png">

**Comment by second2050** [comment]
Oh I didn't see the issue.
Yes it works with YSR as an audio backend so that problem is solved.

Another question from me is could the OpenAL driver crash be related to my sound card (a SoundBlaster X-Fi) because afaik it should have hardware acceleration for OpenAL.

**Comment by yvt** [comment]
The Windows build of OpenSpades is packaged along with OpenAL Soft (`openal32.dll`). Does your sound card support (or emulate) high-end speaker configurations such as surround sound? I suspect that OpenAL Soft might have a problem with such configurations.

The existence of `openal32.dll` in the same directory prevents the detection of the hardware OpenAL support by "shadowing" the system-global `openal32.dll`. Since you seem to have a good sound card, you might be able to have a better experience if you delete the packaged one.

**Comment by second2050** [comment]
Renaming the `openal32.dll` in the game directory fixed the problem and I can use the OpenAL backend again.

My sound card supports multiple surround sound configurations but does not emulate them as far as I know. Maybe it is emulating surround sound configurations because it's set to `Headphones` but I'm not an expert on that matter.

I'm closing the issue now because my problem is solved, thanks for helping me.
