### ISSUE TITLE
2 issues!

### ISSUE THREAD

**Issue by alexdrank** [yvt/openspades#911]
Hello!
1. Where is the splash screen image ( https://prnt.sc/ums20b )? I have looked for it in all the .pak and the resources folder and I have not found it
2. How is the crosshair changed? I have already edited the Sight.tga in the .pak file and it remains the same

**Comment by yvt** [comment]
> 1. Where is the splash screen image ( https://prnt.sc/ums20b )? I have looked for it in all the .pak and the resources folder and I have not found it

It's embedded in the executable file so that it can be displayed while the program is looking for `.pak` files.

> 2. How is the crosshair changed? I have already edited the Sight.tga in the .pak file and it remains the same

That's the right file but editing `.pak` files might prove troublesome for many reasons. Maybe try putting it *outside* a `.pak` file, i.e., `Resources/Gfx/Sight.tga`?

Related article: [Resource loading order](https://github.com/yvt/openspades/wiki/Resource-loading-order#resource-search-order)

**Comment by alexdrank** [comment]
Thank you! I've already been able to change both. Last question, what is the way to play a sound in any case using the scripts written in angelscript? Is there also a function to stop the sound?

**Comment by yvt** [comment]
>  what is the way to play a sound in any case using the scripts written in angelscript?

https://github.com/yvt/openspades/blob/46679c65c4d8794de3f3c4bc78ad30be5e82d6de/Resources/Scripts/Skin/SMG/View.as#L38
https://github.com/yvt/openspades/blob/46679c65c4d8794de3f3c4bc78ad30be5e82d6de/Resources/Scripts/Skin/SMG/View.as#L65
https://github.com/yvt/openspades/blob/46679c65c4d8794de3f3c4bc78ad30be5e82d6de/Resources/Scripts/Skin/SMG/View.as#L80-L83

See <https://github.com/yvt/openspades/blob/master/Resources/Scripts/Reference/API/AudioDevice.as> for the full API.

> Is there also a function to stop the sound?

No, sadly.
