### ISSUE TITLE
[Feature Request] Raytracing

### ISSUE THREAD

**Issue by DrTexx** [yvt/openspades#914]
Okay so, might be a bit of an ambitious request based on the fact the engine appears to be written from scratch, however I believe raytracing could look absolutely incredible in this game.

Some reasons I'm thinking of:
- Vibrant colours
- Environment constantly changing from building/destruction
- Gunfire
- Water
- Seeing a shadow cast over you as a building collapses towards you
    - Perhaps more ambitious than the rest, depends on how the geometry is handled by the engine I'm guessing

Anyway that's it, just thought it was worth mentioning as I'd not seen any other open/closed GH issues on the matter.

Thank you for coming to my TED talk. :scientist:

**Comment by NotAFile** [comment]
this more or less implies completely rewriting the renderer with vulkan. Incredibly unlikely to happen.

**Comment by DrTexx** [comment]
Entirely understandable, thanks for the prompt reply!

Have a great day! :)

**Comment by yvt** [comment]
OpenSpades already uses raytracing when it needs to, and doesn't when it shouldn't. The rendering engine is designed to cover the wide gamut running from the first generation Intel HD Graphics to latest video cards I can't name. This game is designed to make the best of every computer's capability rather than to urge everyone to buy those green GPUs. Another important goal is to keep the gameplay fair and comparable with other clients (vanilla, BetterSpades, etc.).

> - Vibrant colours

The default color adjustment tones down the colors somewhat so they don't look like Citadel Station's Hospital level. You could try adjusting `r_saturation` config variable.

> - Environment constantly changing from building/destruction

Isn't this whole game the epitome of that?

> - Gunfire

All guns in AoS use hitscan—when the player pulls the trigger, it projects a ray in front and the imaginary bullet instantly hits whatever the ray intersects with first. This is somewhat old-fashioned, and not everyone likes that, but that's how the vanilla and all compatible clients work.

> - Water

At the maximum level, the water shader casts up to a total of three rays per pixel to implement reflection and refraction.

> - Seeing a shadow cast over you as a building collapses towards you

Collapsing structures already cast shadows (unless disabled). If they don't, it's probably a bug.

**Comment by DrTexx** [comment]
Totally understandable, thank you for the elaboration!

Just to clarify, my points were referring to things the game _already has_ without any ray-tracing; I wasn't meaning to convey them as missing. I was trying to highlight some aspects of the existing game that would be favourable were ray-tracing feasible.
