### ISSUE TITLE
(suggestion) Add controller support

### ISSUE THREAD

**Issue by Autist69420** [yvt/openspades#958]
For people who prefer controllers over keyboards. If you don't have a controller I'd be glad to help if needed

**Comment by feikname** [comment]
Thanks for the suggestion!

This is already tracked in bug #547, so I will close this as duplicate.

Feel free to leave a thumbs up there, so that when looking for [issues sorted by reactions ](https://github.com/yvt/openspades/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) its more way up there.
